### ISSUE TITLE
HiPay Enterprise - Prestashop 1.7.6.1

### ISSUE THREAD

**Issue by mickaelmaury** [hipay/hipay-enterprise-sdk-prestashop#66]
HiPay Enterprise module does not work on our Prestashop 1.7.6.1 test shop: [https://123plombsps17.mickael-maury.fr/](https://123plombsps17.mickael-maury.fr/)

In DEBUG mode we get errors (Apache PHP version 7.3) - see attached screenshot.
<img width="1274" alt="Capture d’écran 2019-10-30 à 21 35 52" src="https://user-images.githubusercontent.com/23094018/67939003-eda08480-fbd0-11e9-9cde-06dd2897babb.png">

**Comment by JBaptisteLvt** [comment]
Hello,
We are deeply sorry for this answer's delay. Your tests shop is no longer available, so we are not able to test things out.
Did you by any chance install our Professional Module before installing the Enterprise Module ? If that's the case, the issue is most probably an error in the database, which you can overcome by deleting the "HIPAY_CONFIG" line in your configuration table in your database. Caution though : doing so will make you lose all configuration, so please let us know if our initial assumption is incorrect.
Have a nice day,
The HiPay Team
